In [ ]:
Therotical Questions

In [ ]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
# enhance Python's capabilities for numerical operations?
#Ans : NumPy is an indispensable tool for scientific computing, data analysis, and numerical computations in Python.
#Its ability to efficiently handle arrays, perform complex mathematical operations, and seamlessly
#integrate with other libraries solidifies its position as the cornerstone of numerical computing in Python.
#NumPy is a Python library that's used for scientific computing and data analysis because it's fast, efficient,
#and integrates well with other libraries:

#Speed
#NumPy is faster than Python lists for mathematical and logical operations on arrays and matrices.
#This is because NumPy arrays are made up of similar data types and are packed tightly in memory.
#Memory efficiency
#NumPy arrays use contiguous memory blocks, which reduces overhead and makes data access and manipulation faster.
#Mathematical functions
#NumPy has a large collection of mathematical functions for scientific computing, linear algebra, and statistics.
#Integration
#NumPy integrates with other scientific Python libraries, such as SciPy, Pandas, and Matplotlib.
#This allows for a comprehensive suite of tools for data analysis, visualization, and machine learning.
#Broadcasting
#NumPy's broadcasting capability allows for arithmetic operations between arrays of different shapes and sizes.
#Reshaping
#NumPy allows you to change the shape of an array without changing its data. This can be useful for preparing
#data for visualization or other operations.

#Advantages of NumPy

#Performance: NumPy’s array operations are executed at compiled C speed, making them significantly faster than equivalent operations
# using Python lists. This performance boost is vital for handling large datasets and complex computations efficiently.

#Memory Efficiency: NumPy arrays use contiguous memory blocks, reducing overhead compared to Python lists.
#This memory efficiency is essential when dealing with extensive datasets and enables faster data access and manipulation.

#Extensive Mathematical Functions: NumPy provides a rich collection of mathematical functions, making it an indispensable
#tool for scientific computing, linear algebra, statistics, and more. These functions streamline complex calculations and data transformations.

#Interoperability: NumPy integrates with other libraries and tools in the scientific Python ecosystem, such as SciPy,
#Pandas, Matplotlib, and scikit-learn. This integration allows for a comprehensive data analysis, visualization, and machine learning suite.

#NumPy, or Numerical Python, is a crucial package for numerical computing in Python.
#It includes the NumPy array, a powerful multidimensional array that allows for fast and flexible operations on large datasets.
#NumPy is essential for data science, specifically in array manipulation, mathematical operations, and statistical analysis.
#NumPy arrays are more efficient and compact than Python’s built-in sequences, providing faster access for reading and writing items and
#are incredibly efficient with NumPy arrays.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

doubled_arr = arr * 2  # Efficient element-wise multiplication

#NumPy offers a range of numeric datatypes such as int32, int64, float32, float64, complex64, and complex128, improving
#flexibility and efficiency in numerical computations. Selecting the right datatype can greatly influence memory usage and computational speed,
#making NumPy ideal for managing large datasets and high-precision calculations. By explicitly defining datatypes, NumPy ensures efficient
#memory usage and optimal computational performance.

# Creating arrays with specific datatypes
int_array = np.array([1, 2, 3, 4], dtype='int32')
float_array = np.array([1.1, 2.2, 3.3], dtype=np.float64)

# Performing operations with datatype considerations
result = int_array + float_array  # Result is upcasted to float64

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

Output:
[1 2 3 4 5]


In [ ]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
#Ans : In the Numpy library, there are two functions np.mean() and np.average() are present. Both are actually
#4doing nearly the same job of calculating mean/average. The difference comes when we are calculating the weighted average.
#If that is the case then we have to use np.average(). With np.average function we can calculate both arithmetic mean and weighted average.
#In this article, we have shown the basic use case of both functions and how they are different from each other.
#Calculation Approach
#np.mean() calculates the arithmetic mean of the values in an array. It adds up all the values in the
#array and then divides by the total count of values. This results in an unweighted average where every value has the same importance.
#np.average() calculates the average of the values, similar to np.mean(). However, it provides more flexibility.
#It can calculate both simple averages (unweighted) as well as weighted averages based on specified weights.

#Weighted Averages
#np.mean() always computes an unweighted average, treating all values equally.
#Each value contributes the same amount to the final average.
#np.average() can compute both unweighted and weighted averages. Weighted averages allow you to assign different
#levels of importance to individual values. Values with higher weights contribute more to the final average.

#Use Cases
#np.mean() is suitable for scenarios where you want a basic, straightforward average of values without considering different weights.
#For instance, calculating the average height of a group of people.
#np.average() is valuable when dealing with situations where the significance of values varies.
#It's useful when considering factors such as importance, relevance, or impact in the average calculation.
#For example, when calculating a student's final grade, you might assign different weights to assignments, quizzes, and exams.

#Example
#Imagine you have the test scores of a class: [85, 92, 78, 90, 88]. Using np.mean(), you'd calculate (85 + 92 + 78 + 90 + 88) / 5 = 86.6,
#the simple average of the scores.
#Now, consider a course with assignments and a final exam. The assignments are worth 40% and the final exam is worth 60% of the grade.
#You have scores like this: Assignments [80, 95, 88] and Final Exam [75]. Using np.average(), the weighted average would be calculated
#as 0.4 * np.mean(assignments) + 0.6 * np.mean(final_exam) = 86.8, considering the varying weights of assignments and the final exam.

In [ ]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
#Ans : Sometimes while programming in Python, we need to use Python to invert a NumPy array.
#In Python, the reverse of a NumPy array indicates changing the order. The first element will become the last element,
#the second last, the last the first, and so on. There are several methods for reversing a numpy array.

#Some of the most frequent methods for reversing a numpy array are as follows:

#Utilizing the len() with Loops
#Using the list slicing technique
#Using the flip() function
#Using the reverse() function
#Using the flipud() function
#Using the fliplr() function
#Ready? Let's work together to invert some NumPy arrays!

#Using the len() with Loops
#To reverse a list, we may use the len() method also known as the two-pointers approach. A developer coming from another programming
#language may use the following technique. This is a custom approach, not a built-in one. We'll begin by pointing to the first entry on
#our NumPy array. Start with an index variable pointing to zero. We will now proceed to the last entry of our NumPy array, the end index,
# we will compute using the len() method. As a result, these functionalities are dependent on the user's expertise and how they built
#the custom code.

#Consider the following example:

Code:

def reverse(nums):
    start_index = 0
    end_index = len(nums)-1
    while end_index > start_index:
        nums[start_index],nums[end_index] = nums[end_index],nums[start_index]
        start_index = start_index + 1
        end_index = end_index -1

n = [1,2,3,4,5,6,7,8,9,0]
reverse(n)
print(n)

Output:

[0, 9, 8, 7, 6, 5, 4, 3, 2, 1]

#To convert a 1D array to a 2D array in Python, you can use the reshape() method from the NumPy library.
#This method takes the original array and a tuple specifying the desired shape of the new array. Here's how it works:

#Reshaping 1D array to 2D array

#Let's say you have a 1D array with 12 elements that you want to convert to a 2D array with 4 rows and 3 columns.
#Here's how you can do it using NumPy:

1 import numpy as np
2
3 # Create a 1D array with 12 elements
4 arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
5
6 # Reshape the 1D array to a 2D array with 4 rows and 3 columns
7 arr2d = arr1d.reshape(4, 3)
8
9 print(arr2d)

Output:

 1 [[ 1  2  3]
 2 [ 4  5  6]
 3 [ 7  8  9]
 4 [10 11 12]]

#Here, we first create a 1D array with 12 elements using NumPy's array() function. Then, we use the reshape() method to
#convert this array to a 2D array with 4 rows and 3 columns. The resulting array arr2d has 4 rows and 3 columns, as desired.

#Reshaping 1D array to 2D array with Unknown Rows

#If you don't know the number of rows or columns in advance, you can use the -1 placeholder in the reshape() method. Here's an example:

1 import numpy as np
2
3 # Create a 1D array with 12 elements
4 arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
5
6 # Reshape the 1D array to a 2D array with an unknown number of rows and 3 columns
7 arr2d = arr1d.reshape(-1, 3)
8
9 print(arr2d)

Output:

1 [[ 1  2  3]
2  [ 4  5  6]
3  [ 7  8  9]
4  [10 11 12]]

#Here, we use the -1 placeholder in the first argument of the reshape() method to indicate that we want an unknown number of rows.
#NumPy automatically calculates the number of rows based on the number of columns and the total number of elements in the array.
#The resulting array arr2d is the same as in the previous example.

In [ ]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
#Ans : Here, are various ways to check NumPy dtype attributes. here we are discussing some generally used methods for checking
#NumPy dtype attributes those are following.

Using dtype
Using array function array().
Check NumPy dtype Attributes Using dtype
Example 1: Check Integer Datatype

In this example, the code snippet utilizes the NumPy library to create an array, ‘arr,’ containing integers.
The array is then printed along with its datatype, showcasing the flexibility and simplicity of NumPy for numerical operations in Python.

# importing numpy library
import numpy as np

# creating and initializing an array
arr = np.array([1, 2, 3, 23, 56, 100])

# printing the array and checking datatype
print('Array:', arr)

print('Datatype:', arr.dtype)
Output:

Array: [  1   2   3  23  56 100]
Datatype: int32
Example 2 : Check String Datatype

#In this example, the NumPy library is used to create an array (`arr_1`) containing strings like ‘apple’, ‘ball’, ‘cat’, and ‘dog’.
#The script then prints the array and its data type, revealing that the elements are of type Unicode string.


import numpy as np

# creating and initializing array of string
arr_1 = np.array(['apple', 'ball', 'cat', 'dog'])

# printing array and its datatype
print('Array:', arr_1)

print('Datatype:', arr_1.dtype)
Output:

Array: ['a' 'b' 'c' 'd']
Datatype: <U1

Using array function array().
#Creating the array with a defined datatype. Creating numpy array by using an array function array().
#This function takes argument dtype that allows us to define the expected data type of the array elements:

#Example 1: In this example code utilizes the NumPy library to create an array ‘arr’ containing elements [1, 2, 3, 8, 7, 5],
#with a specified datatype ‘S’ (string). The script then prints both the array and its datatype, showcasing the flexibility of NumPy arrays to
#handle various data types.


import numpy as np

# Creating and initializing array with datatype
arr = np.array([1, 2, 3, 8, 7, 5], dtype='S')

# printing array and its datatype
print("Array:", arr)
print("Datatype:", arr.dtype)
Output:

S is used for defining string datatype. We use i, u, f, S and U for defining various other data types along with their size.

Array: [b'1' b'2' b'3' b'8' b'7' b'5']
Datatype: |S1

#Example 2: In this example a NumPy array named ‘arr’ is created and initialized with values [1, 2, 3, 4],
 a 32-bit integer datatype (‘i4’). The array and its datatype are then printed using the NumPy library.


import numpy as np

# creating and initialising array along
# with datatype and its size 4 i.e. 32bytes
arr = np.array([1, 2, 3, 4], dtype='i4')

# printing array and datatype
print('Array:', arr)
print('Datatype:', arr.dtype)

#Data types are important for memory management and performance in programming because they help ensure that the right amount of memory
#is allocated for the data, and that the correct operations are performed on it:

#Memory allocation
#Different data types require different amounts of memory. For example, an integer usually needs less memory than a
#floating-point number because it doesn't need to store decimal places. Choosing the right data type can help reduce memory consumption,
#which can improve performance and scalability.

#Memory access and manipulation
#The choice of data type can affect how memory is accessed and manipulated. Larger data types may require more processing power,
#which can slow down the program.

#Code reliability and efficiency
#Data types help enforce code reliability and efficiency. They ensure that operations performed on the data are appropriate and valid.



In [ ]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
#Ans : An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size.
#The number of dimensions and items in an array is defined by its shape ,
#which is a tuple of N non-negative integers that specify the sizes of each dimension.
#As with other container objects in Python, the contents of an ndarray can be accessed and modified by indexing or slicing the array
#(using, for example, N integers), and via the methods and attributes of the ndarray.

#Different ndarrays can share the same data, so that changes made in one ndarray may be visible in another.
#That is, an ndarray can be a “view” to another ndarray, and the data it is referring to is taken care of by the “base” ndarray.
#ndarrays can also be views to memory owned by Python strings or objects implementing the memoryview or array interfaces.

#1 Example

A 2-dimensional array of size 2 x 3, composed of 4-byte integer elements:

import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
type(x)
<class 'numpy.ndarray'>
x.shape
(2, 3)
x.dtype
dtype('int32')
The array can be indexed using Python container-like syntax:

# The element of x in the *second* row, *third* column, namely, 6.
x[1, 2]
   6
#For example slicing can produce views of the array:

y = x[:,1]
y
array([2, 5], dtype=int32)
y[0] = 9 # this also changes the corresponding element in x
y
array([9, 5], dtype=int32)
x
array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
#Ans :NumPy arrays have several performance benefits over Python lists, including:
#Speed: NumPy arrays are faster than Python lists, especially for large datasets or complex operations. NumPy is built in C and uses
#pre-compiled code for numerical operations.

#Memory usage: NumPy arrays are more memory efficient than Python lists because each item in a NumPy array is the same data type.

#Vectorization: NumPy is designed to be efficient with matrix operations. Vectorization expresses mathematical operations on
#entire arrays, rather than individual elements.

#Broadcasting: NumPy has a broadcasting feature that makes numerical computing efficient.

#Optimized memory management: NumPy has optimized memory management features.

#Compatibility: NumPy is compatible with many other Python libraries used in data science, such as Pandas, Matplotlib, and SciPy.

#Ease of learning: NumPy is relatively easy to learn, especially for those already familiar with Python.
#NumPy arrays are often used in data science, where speed and resources are important.

#Numpy array
#NumPy is the fundamental package for scientific computing in Python. Numpy arrays facilitate advanced mathematical and other types of
#operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using
#Python’s built-in sequences. Numpy is not another programming language but a Python extension module. It provides fast and efficient operations
#on arrays of homogeneous data.

#Some important points about Numpy arrays:

#We can create an N-dimensional array in Python using Numpy.array().
#The array is by default Homogeneous, which means data inside an array must be of the same Datatype.
#(Note You can also create a structured array in Python).
#Element-wise operation is possible.
#Numpy array has various functions, methods, and variables, to ease our task of matrix computation.
#Elements of an array are stored contiguously in memory. For example, all rows of a two-dimensioned array must have the same number of columns.
#A three-dimensional array must have the same number of rows and columns on each card.
#Representation of Numpy array
#Single Dimensional Numpy Array

import numpy as np

a = np.array([1, 2, 3])
print(a)
O

[1 2 3]
Multi-dimensional Numpy Array


import numpy as np

a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
Output:

[[1 2 3]
[4 5 6]]

# Python List?
#A Python list is a collection that is ordered and changeable. In Python, lists are written with square brackets.

#Some important points about Python Lists:

#The list can be homogeneous or heterogeneous.
#Element-wise operation is not possible on the list.
#Python list is by default 1-dimensional. But we can create an N-Dimensional list. But then too it will be 1 D list storing another 1D list
#Elements of a list need not be contiguous in memory.
#Below are some examples which clearly demonstrate how Numpy arrays are better than Python lists by analyzing the
#memory consumption, execution time comparison, and operations supported by both of them.

#Representation of Python List
#Here we are creating Python List using []


Var = ["Geeks", "for", "Geeks"]
print(Var)
Output:

["Geeks", "for", "Geeks"]
Comparison between Numpy array and Python List
#Python Lists
#Element Overhead: Lists in Python store additional information about each element, such as its type and reference count.
#This overhead can be significant when dealing with a large number of elements.
#Datatype: Lists can hold different data types, but this can decrease memory efficiency and slow numerical operations.
#Memory Fragmentation: Lists may not store elements in contiguous memory locations, causing memory fragmentation and inefficiency.
#Performance: Lists are not optimized for numerical computations and may have slower mathematical operations due to Python’s interpretation overhead. They are generally used as general-purpose data structures.
#Functionality: Lists can store any data type, but lack specialized NumPy functions for numerical operations.

#In this example, the incapability of the Python list to carry out a basic operation is demonstrated.
#A Python list and a Numpy array having the same elements will be declared and an integer will be added to increment each
#element of the container by that integer value without looping statements. The effect of this operation on the Numpy array and
#Python list will be analyzed.


# importing Numpy package
import numpy as np

# declaring a list
ls =[1, 2, 3]

# converting the list into a Numpy array
arr = np.array(ls)

try:
    # adding 4 to each element of list
    ls = ls + 4

except(TypeError):
    print("Lists don't support list + int")

# now on array
try:
    # adding 4 to each element of Numpy array
    arr = arr + 4

    # printing the Numpy array
    print("Modified Numpy array: ",arr)

except(TypeError):
    print("Numpy arrays don't support list + int")
Output:

Lists don't support list + int
Modified Numpy array:  [5 6 7]

In [ ]:
#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
#Ans : np.hstack
#The function np.hstack(tup) takes arguments as tuple which include matrix's/arrays. The hstack function combines the
#two or more matrix/arrays horizontally which have the same number of rows. The hstack returns an ndarray.

#Lets us consider an example :

#Generate a random matrix A of size 5,4 and matrix A of size 5,8
import numpy as np
A = np.ones((2,2),int)
B= np.zeros((2,4),int)
print("A:",A,"\n","B:",B)
A: [[1 1]
 [1 1]]
 B: [[0 0 0 0]
 [0 0 0 0]]
passing the matrix A and B into the hstack as a tuple
hstack = np.hstack((A,B))
print(hstack)
[[1 1 0 0 0 0]
 [1 1 0 0 0 0]]
np.vstack
#The function np.vstack(tup) takes arguments as tuple which includes matrix's/arrays. The vstack function
#combines the two or more matrix/arrays vertically which have the same number of columns. The vstack returns an ndarray.

#Let us consider an example:

Consider 2 matrices A and B of size 5,4 and 3,4 respectively.
A = np.ones((3,4))
B = np.zeros((2,4))
print("A:",A,"\n","B:",B)
A: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
 B: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
combining the matrix using np.vstack
vstack = np.vstack((A,B))
print(vstack)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
np.concatenate
#The concatenate function takes several arguments: numpy.concatenate((a1, a2, …), axis=0, out=None) where

a1 a2 are the arrays.
#axis 0 or 1 which specifies whether to concatenate horizontally or vertically.
#out can be provided with the destination array or the output array; by default it's none.
#The concatenate operation can perform both hstack and vstack and it can be specified by setting the axis.
#If the axis is set to 0, it works as vstack and if the axis is 1, it works as hstack.

#Let’s take an example:

#Generate a matrix A and B of size 2,4 and 2,5
#Horizontal concatenation

A = np.ones((2,4))
B = np.zeros((2,5))
print("A:",A,"\n","B:",B)
A: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
 B: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
concatenate with respect to axis =0
out =  np.concatenate((A,B),axis=1)
print(out)
[[1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0.]]
Generate a matrix A and B of size 3,2 and 4,2
Vertical concatenation

A = np.ones((3,2))
B = np.zeros((4,2))
print("A:",A,"\n","B:",B)
A: [[1. 1.]
 [1. 1.]
 [1. 1.]]
 B: [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
#concatenation with respect to axis 0 or vertical
out =  np.concatenate((A,B),axis=0)
print(out)
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
#Ans :vertically: np.flipud()
Use numpy.flipud() to flip ndarray vertically. ud means "Up" and "Down".

#numpy.flipud() returns a view. Because a view shares memory with the original array, changing one value changes the other.

import numpy as np

a_2d = np.arange(6).reshape(2, 3)
print(a_2d)
# [[0 1 2]
#  [3 4 5]]

a_2d_flipud = np.flipud(a_2d)
print(a_2d_flipud)
# [[3 4 5]
#  [0 1 2]]

print(np.shares_memory(a_2d, a_2d_flipud))
# True
If you want to process as separate data, use copy().

a_2d_flipud_copy = np.flipud(a_2d).copy()
print(a_2d_flipud_copy)
# [[3 4 5]
#  [0 1 2]]

print(np.shares_memory(a_2d, a_2d_flipud_copy))
# False
numpy.flipud() is equivalent to slice [::-1]. The array flips along the first axis.

print(a_2d[::-1])
# [[3 4 5]
#  [0 1 2]]

#The same is true for one-dimensional and multi-dimensional arrays of three or more dimensions, where the
#array is flipped along the first axis. In the case of one-dimensional array, it is different from the impression of "vertically", so be careful.

a_1d = np.arange(3)
print(a_1d)
# [0 1 2]

print(np.flipud(a_1d))
# [2 1 0]

print(a_1d[::-1])
# [2 1 0]
a_3d = np.arange(24).reshape(2, 3, 4)
print(a_3d)
# [[[ 0  1  2  3]
#   [ 4  5  6  7]
#   [ 8  9 10 11]]
#
#  [[12 13 14 15]
#   [16 17 18 19]
#   [20 21 22 23]]]

print(np.flipud(a_3d))
# [[[12 13 14 15]
#   [16 17 18 19]
#   [20 21 22 23]]
#
#  [[ 0  1  2  3]
#   [ 4  5  6  7]
#   [ 8  9 10 11]]]

print(a_3d[::-1])
# [[[12 13 14 15]
#   [16 17 18 19]
#   [20 21 22 23]]
#
#  [[ 0  1  2  3]
#   [ 4  5  6  7]
#   [ 8  9 10 11]]]

horizontally: np.fliplr()
#Use numpy.fliplr() to flip ndarray horizontally. lr means "Left" and "Right".

numpy.flipud() returns a view. If you want to process as separate data, you can use copy() as in the example of numpy.flipud().

import numpy as np

a_2d = np.arange(6).reshape(2, 3)
print(a_2d)
# [[0 1 2]
#  [3 4 5]]

a_2d_fliplr = np.fliplr(a_2d)
print(a_2d_fliplr)
# [[2 1 0]
#  [5 4 3]]

print(np.shares_memory(a_2d, a_2d_fliplr))
# True
numpy.fliplr() is equivalent to slice [:, ::-1]. The array flips along the second axis.

print(a_2d[:, ::-1])
# [[2 1 0]
#  [5 4 3]]
#The same is true for one-dimensional and multi-dimensional arrays of three or more dimensions, where the array is flipped
#along the second axis. Note that in the case of a one-dimensional array, an error is raised because the second axis does not exist.

a_1d = np.arange(3)
print(a_1d)
# [0 1 2]

# print(np.fliplr(a_1d))
# ValueError: Input must be >= 2-d.
a_3d = np.arange(24).reshape(2, 3, 4)
print(a_3d)
# [[[ 0  1  2  3]
#   [ 4  5  6  7]
#   [ 8  9 10 11]]
#
#  [[12 13 14 15]
#   [16 17 18 19]
#   [20 21 22 23]]]

print(np.fliplr(a_3d))
# [[[ 8  9 10 11]
#   [ 4  5  6  7]
#   [ 0  1  2  3]]
#
#  [[20 21 22 23]
#   [16 17 18 19]
#   [12 13 14 15]]]

print(a_3d[:, ::-1])
# [[[ 8  9 10 11]
#   [ 4  5  6  7]
#   [ 0  1  2  3]]
#
#  [[20 21 22 23]
#   [16 17 18 19]
#   [12 13 14 15]]]

In [ ]:
#9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
#Ans :NumPy arrays are an essential tool for scientific computing. However, at times, it becomes necessary to manipulate and analyze specific parts of the data. This is where array splitting comes into play, allowing you to break down an array into smaller sub-arrays, making the data more manageable. It is similar to slicing but on a larger scale. NumPy provides various methods that are specifically designed for different use cases and scenarios.

#NumPy Splitting Array
#Array splitting in NumPy is like a slice of cake. Think of each element in a NumPy array as a slice of cake. Splitting divides this “cake”
#into smaller “slices” (sub-arrays), often along specific dimensions or based on certain criteria. We can split horizontally, vertically, or
#even diagonally depending on our needs.

#The split(), hsplit(), vsplit(), and dsplit() functions are important tools for dividing arrays along various axes and dimensions.
#These functions are particularly useful when working with one-dimensional arrays, matrices, or high-dimensional datasets. NumPy’s array-splitting
#capabilities are crucial for enhancing the efficiency and flexibility of data processing workflows.

#Key concepts and terminology
#Here are some important terms to understand when splitting arrays:

#Axis: The dimension along which the array is split (e.g., rows, columns, depth).
#Sub-arrays: The smaller arrays resulting from the split.
#Splitting methods: Different functions in NumPy for splitting arrays (e.g., np.split(), np.vsplit(), np.hsplit(), etc.).
#Equal vs. Unequal splits: Whether the sub-arrays have the same size or not.



import numpy as np
Arr = np.array([1, 2, 3, 4, 5, 6])
array = np.array_split(arr, 3)
print(array)
Output:

[array([1, 2]), array([3, 4]), array([5, 6])]
#Splitting NumPy Arrays in Python
#There are many methods to Split Numpy Array in Python using different functions some of them are mentioned below:

Split numpy array using numpy.split()
Split numpy array using numpy.array_split()
Splitting NumPy 2D Arrays
Split numpy array using numpy.vsplit()
Split numpy array using numpyhsplit()
Split numpy arrayusing numpy.dsplit()

#1. Splitting Arrays Into Equal Parts using numpy.split()
#numpy.split() is a function that divides an array into equal parts along a specified axis. The code imports NumPy creates
#an array of numbers (0-5), and then splits it in half (horizontally) using np.split(). The output shows the original array and the two
#resulting sub-arrays, each containing 3 elements.

import numpy as np

# Creating an example array
array = np.arange(6)

# Splitting the array into 2 equal parts along the first axis (axis=0)
result = np.split(array, 2)

print("Array:")
print(array)
print("\nResult after numpy.split():")
print(result)
Output:

Array:
[0 1 2 3 4 5]
Result after numpy.split():
[array([0, 1, 2]), array([3, 4, 5])]

#2. Unequal Splitting of Arrays using numpy.array_split()
#numpy.array_split() splitting into equal or nearly equal sub-arrays or is similar to numpy.split(),
#but it allows for uneven splitting of arrays. This is useful when the array cannot be evenly divided by the specified number of splits.
#numpy.array_split(array, 4) splits the array into four parts, accommodating the uneven division.

import numpy as np

# Creating an example array
array = np.arange(13)

# Splitting the array into 4 unequal parts along the first axis (axis=0)
result = np.array_split(array, 4)

print("Array:")
print(array)
print("\nResult after numpy.array_split():")
print(result)

Output:

Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
Result after numpy.array_split():
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [ ]:
#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
#Ans :Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python.
#It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are also
#cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation. This article provides a
#gentle introduction to broadcasting with numerous examples ranging from simple to involved. It also provides hints on when and when
#not to use broadcasting.

#numpy operations are usually done element-by-element which requires two arrays to have exactly the same shape:

Example 1
>>> from numpy import array
>>> a = array([1.0, 2.0, 3.0])
>>> b = array([2.0, 2.0, 2.0])
>>> a * b
array([ 2.,  4.,  6.])
#numpy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints.
#The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

Example 2
>>> from numpy import array
>>> a = array([1.0,2.0,3.0])
>>> b = 2.0
>>> a * b
array([ 2.,  4.,  6.])
#The result is equivalent to the previous example where b was an array. We can think of the scalar b being stretched during
#the arithmetic operation into an array with the same shape as a. The new elements in b, as shown in Figure 1, are simply copies
#of the original scalar. The stretching analogy is only conceptual. numpy is smart enough to use the original scalar value without
#actually making copies so that broadcasting operations are as memory and computationally efficient as possible. Because Example 2
#moves less memory, (b is a scalar, not an array) around during the multiplication,
#it is about 10% faster than Example 1 using the standard numpy on Windows 2000 with one million element arrays.


Practical Questions

In [ ]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
#Ans :


In [ ]:
import numpy as np
arr = np.random.randint(1,101,size=(3,3))
print(arr)

In [ ]:
#interchange rows and columns

interchanger_arr = arr.T
print(interchanger_arr)


In [ ]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
#Ans :

In [ ]:
import numpy as np
arr_1d = np.arange(10)
print(arr_1d)


In [ ]:
#reshape it into 2x5

arr_2 = arr_1d.reshape(2,5)
print(arr_2)


In [ ]:
#reshape it into 5x2

arr_3 = arr_2.reshape(5,2)
print(arr_3)

In [ ]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
#Ans :

In [ ]:
import numpy as np
arr = np.random.rand(4,4)
print(arr)


In [ ]:
#add a border of zeros

arr_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr_border)

In [ ]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
#Ans :

In [ ]:
import numpy as np
arr = np.arange(10,61,5)
print(arr)

In [ ]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.
#Ans :

In [ ]:
import numpy as np
arr = np.array(['python', 'numpy', 'pandas'])
print(arr)


In [ ]:
#applying uppercase

arr_upper = np.char.upper(arr)
print(arr_upper)

In [ ]:
#applying lowercase

arr_lower = np.char.lower(arr)
print(arr_lower)


In [ ]:
#applying title case

arr_title = np.char.title(arr)
print(arr_title)

In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
#Ans :

In [ ]:
import numpy as np
words_array = np.array(['pw','skills'])
print(words_array)

In [ ]:
#insert a space between each word

spaced_array = np.char.join(' ', words_array)
print(spaced_array)

In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
#Ans :

In [ ]:
import numpy as np
array1 = np.array([[2,2,3]])
array2 = np.array([[2,2,2]])
print(array1,array2)

In [ ]:
#perform element wise addition

print(array1+array2)

In [ ]:
#subtraction

print(array1-array2)

In [ ]:
#multiplication

print(array1*array2)

In [ ]:
#division

print(array1/array2)

In [ ]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
#Ans :

In [ ]:
import numpy as np
arr = np.eye(5)
print(arr)

In [ ]:
#extract its diagonal elements

print(np.diag(arr))

In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
#Ans :

In [ ]:
import numpy as np

def is_prime(n):
  """Checks if a number is prime."""
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True


In [ ]:
import numpy as np
arr = np.random.randint(0,1001,size=100)
print(arr)


In [ ]:
prime_numbers = [num for num in arr if is_prime(num)]
print("Prime numbers in the array:", prime_numbers)


In [ ]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
#Ans :

In [ ]:
import numpy as np
temperatures = np.random.randint(10,40,size=30)
print(temperatures)


In [ ]:
weekly_averages = np.array_split(temperatures,4)
print(weekly_averages)

In [ ]:
weekly_averages = [np.mean(week) for week in weekly_averages]
print(weekly_averages)

